# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: shibayan/metrics@batch
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: shibayan
          template: classic
          base: header, activity, community, repositories, metadata
          repositories_batch: 50
          config_display: large
          config_timezone: Asia/Tokyo
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_sponsors: yes
          plugin_sponsors_past: yes
          plugin_sponsors_sections: goal, list
          plugin_sponsors_size: 24
          plugin_sponsors_title: Sponsor Me!
